services:
  - type: web
    name: bondoo-api
    runtime: node
    region: frankfurt
    repo: https://github.com/mackings/bondoo-server
    branch: main
    autoDeploy: true
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: "*"
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: BANK_BTC_ADDRESS
        sync: false
      - key: ESCROW_DEPOSIT_ADDRESS
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_FROM_NAME
        value: BondooApp
      - key: BYBIT_API_KEY
        sync: false
      - key: BYBIT_API_SECRET
        sync: false
      - key: BYBIT_TESTNET_API_KEY
        sync: false
      - key: BYBIT_TESTNET_API_SECRET
        sync: false
      - key: BYBIT_TESTNET
        value: "true"
      - key: AGORA_APP_ID
        value: d454d5abab694b20ae57c6a5b4953e0a
      - key: AGORA_APP_CERTIFICATE
        sync: false
      - key: AGORA_TOKEN_TTL_SECONDS
        value: "3600"
